src/components/Content.js
Reverts overture-stack/website#14
=> Revert "Anchors to allow direct links from footer"

src/components/Footer/index.js, src/pages/contact/index.js, src/pages/contact/styles.scss, src/pages/index.js, src/pages/products/ego/index.js
home page copy + styles
add `contact` footer link
contact copy styling
=> changes 66 through 69 on gdoc

gatsby-config.js, package-lock.json, package.json
Adds google analytics plugin + config to `gatsby-config`
=> Add google analytics.

src/pages/contact/index.js, src/pages/index.js, src/pages/products/ego/index.js, src/pages/products/jukebox/index.js, src/pages/products/score/index.js, src/pages/products/song/index.js, src/pages/services/index.js
Jukebox is missing the metadata description. Will update when I get it and we can merge.
=> Add metadata

src/components/MarketingSection/index.js, src/components/MarketingSection/styles.scss, src/components/index.js, src/pages/contact/index.js, src/pages/contact/styles.scss, src/pages/our-vision/index.js, src/pages/our-vision/styles.scss, src/pages/privacy/styles.scss, src/pages/services/index.js, src/pages/services/styles.scss
Some additional cleanup / DRY'ing out some code, from #54 
- Implement Hero Component
- Create a `MarketingSection` (used on `services` and `our vision`)
=> Refactor heroes and create marketing section component.

src/components/CaseStudy/index.js, src/components/Hero/index.js, src/components/Icon/index.js, src/components/ImageCrossfade/index.js, src/components/ProductHero/index.js, src/components/Typography/index.js, src/components/index.js, src/pages/about-us/index.js, src/pages/case-studies/index.js, src/pages/case-studies/navigation.js, src/pages/contact/index.js, src/pages/documentation/index.js, src/pages/index.js, src/pages/privacy/index.js, src/pages/products/arranger/index.js, src/pages/products/ego/index.js, src/pages/products/index.js, src/pages/products/jukebox/index.js, src/pages/products/maestro/index.js, src/pages/products/oncojs/index.js, src/pages/products/persona/index.js, src/pages/products/riff/index.js, src/pages/products/score/index.js, src/pages/products/song/index.js, src/pages/services/index.js, src/pages/terms-conditions/index.js
This reverts commit 788ea51eff48e75f4cdc99ed78115923c09ec252.
Merged this by accident, force of habit.
=> Revert "Docs - add alt attributes & adjust heading levels (#106)"

constants/docs.js, markdown/documentation/dms/admin-guide/tasks.md, netlify.toml, src/components/LinkHelper/index.js, src/pages/case-studies/styles.scss
- update DMS links
- make internal links HTML links to fix blank page issue (temporary)
- make text in Case Studies carousel darker
=> Docs - pre-deploy fixes

markdown/documentation/maestro/installation/configuration.md, markdown/documentation/maestro/installation/installation.md
@blabadi, if you don't mind doing final review of `configuration.md`.  I just did a bit of wordsmithing and reorganization of the new content, hope you don't mind.  No rush for today, edits are very small, netlify here:
https://6070b710023b0c4d23fe43a7--overture.netlify.app/documentation/maestro/installation/configuration/
Thanks!
=> Maestro minor edits

src/components/NavBar/MegaMenu/index.js, src/pages/documentation/index.js
maestro docs are ready, so I removed the comingSoon flag
=> enable maestro docs

src/components/NavBar/MegaMenu/index.js, src/pages/documentation/index.js
remove coming soon flags for score docs
=> enable score docs

README.md, package.json
- specify node version
- specify gatsby-cli version
=> chore: update readme & specify node version

markdown/documentation/dms/admin-guide/common-problems.md, markdown/documentation/dms/installation/installation/index.md
Added disclaimer on installation instructions and a section within the common problems page.
=> Dms compatibility docs update hotfix

markdown/documentation/arranger/index.md, markdown/documentation/arranger/installation/authentication.md, markdown/documentation/arranger/installation/configuration/app.md, markdown/documentation/arranger/installation/configuration/es.md, markdown/documentation/arranger/installation/configuration/metadata.md, markdown/documentation/arranger/installation/installation.md, markdown/documentation/arranger/reference/sqon.md, markdown/documentation/dms-ui/index.md, markdown/documentation/dms-ui/installation/configuration/arranger.md, markdown/documentation/dms-ui/installation/configuration/ego.md, markdown/documentation/dms-ui/installation/configuration/index.md, markdown/documentation/dms-ui/installation/installation.md
- <a> tags replacing []() with target="_blank" and rel="noopener noreferrer"
- Updated .env sample with correct port
=> [Arranger + DMS-UI Docs] Fixed Links, updated .env.local sample

src/pages/acknowledgements/index.js, src/pages/acknowledgements/styles.scss
=> acknowledgmentsPagePolish

src/components/Hero/styles.scss, src/components/ServicesPageSection/index.js, src/components/ServicesPageSection/styles.scss, src/pages/services/index.js
To do
Separate items:
- Discuss with Patrick an embedded email component (can be put on a Contact Us page)
- A simple contact us page
=> servicePagePolish

constants/external-links.js
=> Merge Back

src/data/case_studies/index.js
updated VirusSeq portal link in case studies
=> Update virusSeq portal link

src/pages/404.js, src/styles/_colors.scss, src/styles/main.scss
Updated 404 page to match website refresh theming: The 404 page uses Beluma, I overwrote the hero theming in main.scss to use the background colour $blue-top, this is the colour we use in the hero sections since last update.
**Preview link to updated page:** https://deploy-preview-379--overture.netlify.app/404
=> Minor update to 404 page

markdown/documentation/score/user-guide/download.md
Minor changes to wording in Score documentation
=> minor docs wording fixes

constants/external-links.js, src/data/case_studies/index.js
Link updated & unnecessary link removed
=> Updated KF link

markdown/documentation/guides/download/clientdownload.md
=> Remove extra quotation

markdown/documentation/guides/administration/introduction.md, markdown/documentation/guides/download/clientdownload.md, markdown/documentation/guides/index.md, markdown/documentation/guides/submission/clientsubmission.md, src/pages/getting-started/index.js, src/pages/index.js
Updated bat commands to ensure they run properly
=> Windows command update

markdown/documentation/guides/administration/indexmapping.md, markdown/documentation/guides/administration/introduction.md, markdown/documentation/guides/administration/modelling.md, markdown/documentation/guides/administration/portalcustomization.md, markdown/documentation/guides/deployment/dataportal.md, markdown/documentation/guides/deployment/oauth.md, markdown/documentation/guides/download/clientdownload.md, markdown/documentation/guides/index.md, markdown/documentation/guides/submission/clientsubmission.md, src/pages/getting-started/index.js, src/pages/index.js
Fulfilling requirements set here: https://github.com/overture-stack/conductor/pull/29
- Replace conductor references with quickstart
=> Conductor > Quickstart
